package GUI;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import SourcePackages.Controller;
import SourcePackages.FileHandler;
import SourcePackages.Subject;
import java.util.ArrayList;
import java.util.Collections;

/**
 *
 * @author Bastian Buhrkall
 */
public class MainWindow extends javax.swing.JFrame {
    
    public static ArrayList arr = new ArrayList();
    /**
     * Creates new form MainWindow
     */
    

    public MainWindow() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJPanel = new javax.swing.JPanel();
        forslagLabel = new javax.swing.JLabel();
        loadButton = new java.awt.Button();
        instructionLabel = new javax.swing.JLabel();
        scrollPane1 = new java.awt.ScrollPane();
        subjectGuiList = new java.awt.List();
        overSkrifttLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        beskrivelseTextArea = new javax.swing.JTextArea();
        beskrivelseLabel = new javax.swing.JLabel();
        lærerLabel = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        mainJPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        forslagLabel.setText("Forslag");
        mainJPanel.add(forslagLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, -1, -1));

        loadButton.setActionCommand("button1");
        loadButton.setEnabled(false);
        loadButton.setLabel("Indlæs");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });
        mainJPanel.add(loadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 500, 80, 40));

        instructionLabel.setText("Venligst marker de ønskede");
        mainJPanel.add(instructionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));

        subjectGuiList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectGuiListActionPerformed(evt);
            }
        });
        scrollPane1.add(subjectGuiList);

        mainJPanel.add(scrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 200, 340));

        overSkrifttLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        overSkrifttLabel.setText("Overskrift");
        mainJPanel.add(overSkrifttLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        beskrivelseTextArea.setColumns(20);
        beskrivelseTextArea.setRows(5);
        jScrollPane1.setViewportView(beskrivelseTextArea);

        mainJPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 280, 210));

        beskrivelseLabel.setText("Beskrivelse");
        mainJPanel.add(beskrivelseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        lærerLabel.setText("Lærer");
        mainJPanel.add(lærerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        jCheckBox1.setText("jCheckBox1");
        mainJPanel.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // TODO add your handling code here:
        SourcePackages.FileHandler fileHandler  = new FileHandler();
        populateList(fileHandler.Reader(),subjectGuiList);

    }//GEN-LAST:event_loadButtonActionPerformed

    private void subjectGuiListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectGuiListActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_subjectGuiListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel beskrivelseLabel;
    private javax.swing.JTextArea beskrivelseTextArea;
    private javax.swing.JLabel forslagLabel;
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Button loadButton;
    private javax.swing.JLabel lærerLabel;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JLabel overSkrifttLabel;
    private java.awt.ScrollPane scrollPane1;
    private java.awt.List subjectGuiList;
    // End of variables declaration//GEN-END:variables
    // Populating a JList with an array. Should be in the controller

     
    public void populateList(ArrayList array,java.awt.List jList)
    {
        for(int i =0; i<array.size(); i++)
        {
             //SourcePackages.Subject s1 = (SourcePackages.Subject) array.get(i);
             //javax.swing.JCheckBox checkBox = new javax.swing.JCheckBox();
             //checkBox.setText(s1.getTitle());
             //OBS!!! IKKE FÆRDIG
             //jList.add;
        }        
    }
    //End of populater
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            arr.add("1");
            arr.add("2");
            arr.add("3");
            arr.add("4");
            arr.add("5");
            
            //populateList(arr,list1);
   
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {

                new MainWindow().setVisible(true);
            }
        });
    }
    
    
}
