/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controller.FileHandler;
import Model.Subject;
import java.util.ArrayList;
import Controller.Controller;
import javax.swing.DefaultListModel;

/**
 *
 * @author Charlesmaten
 */
public class ProposalGui extends javax.swing.JFrame {

    /**
     * Creates new form ProposalGui
     */
    DefaultListModel listModel = new DefaultListModel();
    
    ArrayList<Subject> CreateProposal = new ArrayList();
    FileHandler fileHandler;
    Controller con;
    
    public ProposalGui() {
        initComponents();
        fileHandler = new FileHandler();
        con = new Controller();
        ListForslået.setModel(listModel);         
        con.populateList(fileHandler.Reader(con.bastianSørenProposedFile), listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaBeskrivelse = new javax.swing.JTextArea();
        TextFieldOverskrift = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListForslået = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        ButtonTilføj = new javax.swing.JButton();
        TextFieldLærer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextFieldNavn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        LabelMissing = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextAreaBeskrivelse.setColumns(20);
        TextAreaBeskrivelse.setRows(5);
        jScrollPane1.setViewportView(TextAreaBeskrivelse);

        TextFieldOverskrift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldOverskriftActionPerformed(evt);
            }
        });

        jLabel1.setText("Overskrift");

        jLabel2.setText("Beskrivelse");

        ListForslået.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ListForslået);

        jLabel3.setText("Allerede forslået");

        ButtonTilføj.setText("Tilføj");
        ButtonTilføj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTilføjActionPerformed(evt);
            }
        });

        TextFieldLærer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldLærerActionPerformed(evt);
            }
        });

        jLabel4.setText("Forslå lærer");

        TextFieldNavn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNavnActionPerformed(evt);
            }
        });

        jLabel5.setText("Navn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(TextFieldOverskrift, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(100, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldLærer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(ButtonTilføj)
                        .addGap(145, 145, 145)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(TextFieldNavn))
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(105, 105, 105))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelMissing, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldOverskrift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldNavn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonTilføj)
                    .addComponent(TextFieldLærer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(LabelMissing, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldOverskriftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldOverskriftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldOverskriftActionPerformed

    private void ButtonTilføjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTilføjActionPerformed
        
        String navn = TextFieldNavn.getText();
        String overskrift = TextFieldOverskrift.getText();
        String beskrivelse = TextAreaBeskrivelse.getText();
        String lærer = TextFieldLærer.getText();
        
        if(navn.isEmpty()){
            LabelMissing.setText("Mangler navn");
        }
        if(overskrift.isEmpty()){
            LabelMissing.setText("Mangler overskrift");
        }
        if(beskrivelse.isEmpty()){
            LabelMissing.setText("Mangler beskrivelse");
        }
        if(lærer.isEmpty()){
            LabelMissing.setText("Mangler lærer");
        }
        
        if(!lærer.isEmpty() && !navn.isEmpty() && !overskrift.isEmpty() && !beskrivelse.isEmpty()){
        
        Subject sub1 = new Subject(TextFieldNavn.getText(), TextFieldOverskrift.getText(), TextAreaBeskrivelse.getText(), TextFieldLærer.getText());
        CreateProposal.add(sub1);
       
        fileHandler.Writer(CreateProposal, con.bastianSørenProposedFile);
       
        TextFieldNavn.setText("");
        TextFieldOverskrift.setText("");
        TextAreaBeskrivelse.setText("");
        TextFieldLærer.setText("");
        CreateProposal.clear();
        } else{
            LabelMissing.setText("Fejl i forslag");
        }
    }//GEN-LAST:event_ButtonTilføjActionPerformed

    private void TextFieldLærerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldLærerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldLærerActionPerformed

    private void TextFieldNavnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNavnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNavnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProposalGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProposalGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProposalGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProposalGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProposalGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonTilføj;
    private javax.swing.JLabel LabelMissing;
    private javax.swing.JList ListForslået;
    private javax.swing.JTextArea TextAreaBeskrivelse;
    private javax.swing.JTextField TextFieldLærer;
    private javax.swing.JTextField TextFieldNavn;
    private javax.swing.JTextField TextFieldOverskrift;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
